variables:
    CI_PATH: "/home/ubuntu/project"
    CI_TEST_PATH: "/home/ubuntu/project-test"

stages:
    - prepare
    - build
    - test
    - deploy
    - clean

test-copy-repository:
    stage: prepare
    only:
        - merge_requests
    script:
        - sudo rm -rf $CI_TEST_PATH
        - sudo cp -r $CI_PROJECT_DIR $CI_TEST_PATH

test-stop-server:
    stage: prepare
    only:
        - merge_requests
    script:
        - sudo kill `ps -aux | grep 'backend-0.0.1-SNAPSHOT-TEST.jar' | grep -v grep | awk '{print $2}'`
    allow_failure: true

test-backend-build:
    stage: prepare
    only:
        - merge_requests
    script:
        - cd $CI_TEST_PATH/backend
        - sudo cp /home/ubuntu/application.test.properties $CI_TEST_PATH/backend/src/main/resources/application.properties
        - echo $CI_TEST_PATH/backend/src/main/resources/application.properties
        - sudo mvn package
        - sudo rm -rf /home/ubuntu/jar-test
        - sudo mv $CI_TEST_PATH/backend/target /home/ubuntu/jar-test
        - cd /home/ubuntu/jar-test
        - sudo mv backend-0.0.1-SNAPSHOT.jar backend-0.0.1-SNAPSHOT-TEST.jar
        - nohup java -jar backend-0.0.1-SNAPSHOT-TEST.jar > /dev/null 2>&1 &
        - echo `ps -aux | grep 'backend-0.0.1-SNAPSHOT-TEST.jar' | grep -v grep | awk '{print $2}'`

test-frontend:
    stage: test
    only:
        - merge_requests
    script:
        - cd $CI_TEST_PATH/frontend
        - sudo yarn install
        - sudo yarn build

test-backend:
    stage: test
    only:
        - merge_requests
    script:
        - sudo kill `ps -aux | grep 'backend-0.0.1-SNAPSHOT-TEST.jar' | grep -v grep | awk '{print $2}'`

        
        
test-clean-up:
    stage: clean
    only:
        - merge_requests
    script:
        - sudo rm -rf $CI_TEST_PATH

copy-repository:
    stage: prepare
    only:
        - master
    script:
        - sudo rm -rf $CI_PATH
        - sudo cp -r $CI_PROJECT_DIR $CI_PATH

stop-server:
    stage: prepare
    only:
        - master
    script:
        - sudo kill `ps -aux | grep 'backend-0.0.1-SNAPSHOT.jar' | grep -v grep | awk '{print $2}'`
    allow_failure: true

frontend-build:
    stage: build
    only:
        - master
    script:
        - pwd
        - cd $CI_PATH/frontend
        - sudo yarn install
        - sudo yarn build

backend-build:
    stage: build
    only:
        - master
    script:
        - pwd
        - cd $CI_PATH/backend
        - sudo cp /home/ubuntu/application.properties $CI_PATH/backend/src/main/resources/application.properties
        - sudo mvn package

frontend-deploy:
    stage: deploy
    only: 
        - master
    script:
        - sudo rm -rf /home/ubuntu/dist
        - sudo mv $CI_PATH/frontend/dist /home/ubuntu/dist
        - sudo service nginx restart

backend-deploy:
    stage: deploy
    only: 
        - master
    script:
        - sudo rm -rf /home/ubuntu/jar
        - sudo mv $CI_PATH/backend/target /home/ubuntu/jar
        - cd /home/ubuntu/jar
        - nohup java -jar backend-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &

clean-up:
    stage: clean
    only:
        - master
    script:
        - sudo rm -rf $CI_PATH
