variables:
    CI_BUILD_PATH: "/home/ubuntu/project"
    CI_TEST_BUILD_PATH: "/home/ubuntu/project-test"
    CI_RESOURCE_PATH: "/home/ubuntu"
    CI_DISTRIBUTE_PATH: "/home/ubuntu"

stages:
    - prepare
    - build
    - test
    - deploy
    - clean

test-copy-repository:
    stage: prepare
    only:
        - merge_requests
    script:
        - sudo rm -rf $CI_TEST_BUILD_PATH
        - sudo cp -r $CI_PROJECT_DIR $CI_TEST_BUILD_PATH

test-backend-build:
    stage: test
    only:
        - merge_requests
    script:
        - cd $CI_TEST_BUILD_PATH/backend
        - sudo cp $CI_RESOURCE_PATH/application.test.properties $CI_TEST_BUILD_PATH/backend/src/main/resources/application.properties
        - sudo mvn package
        - sudo mv $CI_TEST_BUILD_PATH/backend/target $CI_DISTRIBUTE_PATH/jar-test
        - cd $CI_DISTRIBUTE_PATH/jar-test
        - sudo mv backend-0.0.1-SNAPSHOT.jar backend-0.0.1-SNAPSHOT-TEST.jar
        - nohup java -jar backend-0.0.1-SNAPSHOT-TEST.jar > /dev/null 2>&1 &
        - echo `ps -aux | grep 'backend-0.0.1-SNAPSHOT-TEST.jar' | grep -v grep | awk '{print $2}'`

test-frontend:
    stage: test
    only:
        - merge_requests
    script:
        - sudo cp $CI_RESOURCE_PATH/initKakao.js $CI_TEST_BUILD_PATH/frontend/src/initKakao.js
        - cd $CI_TEST_BUILD_PATH/frontend
        - sudo yarn install
        - sudo yarn build

test-backend:
    stage: test
    only:
        - merge_requests
    script:
        - sudo kill `ps -aux | grep 'backend-0.0.1-SNAPSHOT-TEST.jar' | grep -v grep | awk '{print $2}'`

test-clean-up:
    stage: clean
    only:
        - merge_requests
    script:
        - sudo rm -rf $CI_DISTRIBUTE_PATH/jar-test
        - sudo rm -rf $CI_TEST_BUILD_PATH
        - sudo kill `ps -aux | grep 'backend-0.0.1-SNAPSHOT-TEST.jar' | grep -v grep | awk '{print $2}'`; echo STOP_SERVER
    when: always
    allow_failure: true

copy-repository:
    stage: prepare
    only:
        - master
    script:
        - sudo rm -rf $CI_BUILD_PATH
        - sudo cp -r $CI_PROJECT_DIR $CI_BUILD_PATH

stop-server:
    stage: prepare
    only:
        - master
    script:
        - sudo kill `ps -aux | grep 'backend-0.0.1-SNAPSHOT.jar' | grep -v grep | awk '{print $2}'`
    allow_failure: true

frontend-build:
    stage: build
    only:
        - master
    script:
        - sudo cp $CI_RESOURCE_PATH/initKakao.js $CI_BUILD_PATH/frontend/src/initKakao.js
        - cd $CI_BUILD_PATH/frontend
        - sudo yarn install
        - sudo yarn build

backend-build:
    stage: build
    only:
        - master
    script:
        - pwd
        - cd $CI_BUILD_PATH/backend
        - sudo cp $CI_RESOURCE_PATH/application.properties $CI_BUILD_PATH/backend/src/main/resources/application.properties
        - sudo mvn package

frontend-deploy:
    stage: deploy
    only: 
        - master
    script:
        - sudo rm -rf $CI_DISTRIBUTE_PATH/dist
        - sudo mv $CI_BUILD_PATH/frontend/dist $CI_DISTRIBUTE_PATH/dist
        - sudo service nginx restart

backend-deploy:
    stage: deploy
    only: 
        - master
    script:
        - sudo rm -rf $CI_DISTRIBUTE_PATH/jar
        - sudo mv $CI_BUILD_PATH/backend/target $CI_DISTRIBUTE_PATH/jar
        - cd $CI_DISTRIBUTE_PATH/jar
        - nohup java -jar backend-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &

clean-up:
    stage: clean
    only:
        - master
    script:
        - sudo rm -rf $CI_BUILD_PATH
    when: always
